version: "3"

services:
  db:
    container_name: devicenet-postgres-lab
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=devicenet
      - POSTGRES_USER=devicenet
      - POSTGRES_PASSWORD=devicenet
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 3s
      timeout: 1s
      retries: 10
volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\volumes\devicenet\postgres
