version: "3"
networks:
  lab:
    driver: bridge

services:
  db:
    container_name: devicenet-svc-lab-postgres
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=devicenet
      - POSTGRES_USER=devicenet
      - POSTGRES_PASSWORD=devicenet
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - lab
  lambdaorm-api:
    depends_on:
      - db
    container_name: devicenet-svc-lab-api
    build:
      context: ./../../..
    environment:
      - HOST=http://localhost
      - PORT=9291
      - WORKSPACE=/workspace
      - USERS_SECRET_KEY=rifk863hmKSJDJ87hd*nhJ98
      - DEVICES_SECRET_KEY=hhd843hf8HD7HDg65GD&^5
      - 'CNN_POSTGRES={"host":"devicenet-svc-lab-postgres","port":5432,"user":"devicenet","password":"devicenet","database":"devicenet"}'
    ports:
      - 9291:9291
    expose:
      - 9291
    networks:
      - lab
    volumes:
      - workspace:/workspace
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - lab
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - lab
volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\volumes\devicenet\postgres
  workspace:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\volumes\devicenet\workspace
  prometheus_data: {}
  grafana_data: {}
