app:
  src: src
  data: data
  model: model
enums:
entities:
  - name: Address
    abstract: true
    indexes:
      - name: postalCode
        fields: ["postalCode"]
      - name: region
        fields: ["region", "country"]
      - name: city
        fields: ["city"]
    properties:
      - name: address
      - name: city
      - name: region
      - name: postalCode
        length: 20
      - name: country
  - name: Categories
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: name
        nullable: false
      - name: description
        length: 1000
  - name: Customers
    extends: Address
    primaryKey: ["id"]
    indexes:
      - name: name
        fields: ["name"]
    properties:
      - name: id
        length: 5
        nullable: false
      - name: name
        nullable: false
      - name: contact
      - name: phone
    relations:
      - name: orders
        type: manyToOne
        composite: true
        from: id
        entity: Orders
        to: customerId
  - name: Employees
    extends: Address
    primaryKey: ["id"]
    uniqueKey: ["lastName", "firstName"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: lastName
        nullable: false
      - name: firstName
        nullable: false
      - name: title
      - name: titleOfCourtesy
      - name: birthDate
        type: datetime
      - name: hireDate
        type: datetime
      - name: phone
      - name: reportsToId
        type: integer
    relations:
      - name: reportsTo
        from: reportsToId
        entity: Employees
        to: id
  - name: Shippers
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: name
        nullable: false
      - name: phone
        length: 20
  - name: Suppliers
    extends: Address
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: name
        nullable: false
      - name: contact
      - name: phone
        length: 20
      - name: homepage
        length: 200
  - name: Products
    primaryKey: ["id"]
    uniqueKey: ["name", "supplierId"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: name
        nullable: false
      - name: supplierId
        nullable: false
        type: integer
      - name: categoryId
        type: integer
      - name: quantity
      - name: price
        type: decimal
        default: 0
      - name: inStock
        type: decimal
        default: 0
      - name: onOrder
        type: decimal
        default: 0
      - name: reorderLevel
        type: decimal
        default: 0
      - name: discontinued
        type: boolean
        default: false
    relations:
      - name: supplier
        from: supplierId
        entity: Suppliers
        to: id
      - name: category
        from: categoryId
        entity: Categories
        to: id
  - name: Orders
    primaryKey: ["id"]
    indexes:
      - name: orderDate
        fields: ["orderDate"]
      - name: shippedDate
        fields: ["shippedDate"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: customerId
        nullable: false
        length: 5
      - name: employeeId
        nullable: false
        type: integer
      - name: orderDate
        type: datetime
      - name: requiredDate
        type: datetime
      - name: shippedDate
        type: datetime
      - name: shipViaId
        type: integer
      - name: freight
        type: decimal
      - name: name
      - name: address
      - name: city
      - name: region
      - name: postalCode
        length: 20
      - name: country
    relations:
      - name: customer
        from: customerId
        entity: Customers
        to: id
      - name: employee
        from: employeeId
        entity: Employees
        to: id
      - name: details
        type: manyToOne
        composite: true
        from: id
        entity: OrderDetails
        to: orderId
  - name: OrderDetails
    primaryKey: ["orderId", "productId"]
    properties:
      - name: orderId
        nullable: false
        type: integer
      - name: productId
        nullable: false
        type: integer
      - name: unitPrice
        type: decimal
      - name: quantity
        type: decimal
      - name: discount
        type: decimal
    relations:
      - name: order
        from: orderId
        entity: Orders
        to: id
      - name: product
        from: productId
        entity: Products
        to: id
mappings:
  - name: northwind
    entities:
      - name: Address
        abstract: true
        properties:
          - name: address
            mapping: Address
          - name: city
            mapping: City
          - name: region
            mapping: Region
          - name: postalCode
            mapping: PostalCode
          - name: country
            mapping: Country
      - name: Categories
        mapping: Categories
        properties:
          - name: id
            mapping: CategoryID
          - name: name
            mapping: CategoryName
          - name: description
            mapping: Description
      - name: Customers
        extends: Address
        mapping: Customers
        properties:
          - name: id
            mapping: CustomerID
          - name: name
            mapping: CompanyName
          - name: contact
            mapping: ContactName
          - name: phone
            mapping: ContactTitle
      - name: Employees
        extends: Address
        mapping: Employees
        properties:
          - name: id
            mapping: EmployeeID
          - name: lastName
            mapping: LastName
          - name: firstName
            mapping: FirstName
          - name: title
            mapping: Title
          - name: titleOfCourtesy
            mapping: TitleOfCourtesy
          - name: birthDate
            mapping: BirthDate
          - name: hireDate
            mapping: HireDate
          - name: phone
            mapping: HomePhone
          - name: reportsToId
            mapping: ReportsTo
      - name: Shippers
        mapping: Shippers
        properties:
          - name: id
            mapping: ShipperID
          - name: name
            mapping: CompanyName
          - name: phone
            mapping: Phone
      - name: Suppliers
        extends: Address
        mapping: Suppliers
        properties:
          - name: id
            mapping: SupplierID
          - name: name
            mapping: CompanyName
          - name: contact
            mapping: ContactName
          - name: phone
            mapping: Phone
          - name: homepage
            mapping: HomePage
      - name: Products
        mapping: Products
        properties:
          - name: id
            mapping: ProductID
          - name: name
            mapping: ProductName
          - name: supplierId
            mapping: SupplierID
          - name: categoryId
            mapping: CategoryID
          - name: quantity
            mapping: QuantityPerUnit
          - name: price
            mapping: UnitPrice
          - name: inStock
            mapping: UnitsInStock
          - name: onOrder
            mapping: UnitsOnOrder
          - name: reorderLevel
            mapping: ReorderLevel
          - name: discontinued
            mapping: Discontinued
      - name: Orders
        mapping: Orders
        properties:
          - name: id
            mapping: OrderID
          - name: customerId
            mapping: CustomerID
          - name: employeeId
            mapping: EmployeeID
          - name: orderDate
            mapping: OrderDate
          - name: requiredDate
            mapping: RequiredDate
          - name: shippedDate
            mapping: ShippedDate
          - name: shipViaId
            mapping: ShipVia
          - name: freight
            mapping: Freight
          - name: name
            mapping: ShipName
          - name: address
            mapping: ShipAddress
          - name: city
            mapping: ShipCity
          - name: region
            mapping: ShipRegion
          - name: postalCode
            mapping: ShipPostalCode
          - name: country
            mapping: ShipCountry
      - name: OrderDetails
        mapping: Order Details
        properties:
          - name: orderId
            mapping: OrderID
          - name: productId
            mapping: ProductID
          - name: unitPrice
            mapping: UnitPrice
          - name: quantity
            mapping: Quantity
          - name: discount
            mapping: Discount
dataSources:
  - name: source
    mapping: northwind
    dialect: mysql
    connection: $ORM_CNN_SOURCE
  - name: mysql
    mapping: northwind
    dialect: mysql
    connection: $ORM_CNN_MYSQL
  - name: mariadb
    mapping: northwind
    dialect: mariadb
    connection: $ORM_CNN_MARIADB
  - name: postgres
    mapping: northwind
    dialect: postgres
    connection: $ORM_CNN_POSTGRES
  - name: mssql
    mapping: northwind
    dialect: mssql
    connection: $ORM_CNN_MSSQL
stages:
  - name: source
    dataSources:
      - name: source
  - name: mysql
    dataSources:
      - name: mysql
  - name: mariadb
    dataSources:
      - name: mariadb
  - name: postgres
    dataSources:
      - name: postgres
  - name: mssql
    dataSources:
      - name: mssql
