version: "3"

services:
  db:
    container_name: lambdaorm-svc-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - source:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "status" ]
      interval: 3s
      timeout: 1s
      retries: 10
  svc:
    depends_on:
      - db
    container_name: lambdaorm-svc
    image: flaviorita/lambdaorm-svc:0.0.14
    restart: always
    environment:
      - HOST=http://localhost
      - PORT=9289
      - WORKSPACE=/workspace
      - 'ORM_CNN_POSTGRES={"host":"0.0.0.0","port":5432,"user":"test","password":"test","database":"northwind"}'
      - 'ORM_CNN_SOURCE={"host":"lambdaorm-svc-mysql","port":3306,"user":"test","password":"test","database":"northwind","multipleStatements":true,"waitForConnections":true, "connectionLimit":10,"queueLimit":0}'
    ports:
      - 9289:9289
    volumes:
      - workspace-data:/workspace
volumes:
  workspace-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\volumes\workspace
  source:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\volumes\source
  # postgres:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: C:\volumes\postgres
